#version 450
layout(local_size_x = 1) in;

layout(set = 0, binding = 0) uniform sampler2D uTexture;

layout(set = 0, binding = 1) uniform sampler2D u223;

layout(set = 0, binding = 2) buffer uBuffer
{
    vec4 samples[];
};

void main()
{
    float u = float(gl_GlobalInvocationID.x) / 223.0;

    samples[gl_GlobalInvocationID.x] = vec4(textureLod(uTexture, vec2(u, 0.5), 0.0).x, u, u * textureLod(u223, vec2(0.5, 0.5), 0.0).x, 0);
}